@startuml

class ObservableObject {
}

class RelayCommand {
}

class SportifyController {
  + Run(): void
}

class HomePage {
  - sport: Sport
}

class Sport {
  + Get: string
  + Parameters: SportParameters
  + Errors: List<object>
  + Results: int
  + Responses: List<SportResponse>
}

class SportTeamHome {
  + Id: int
  + Name: string
  + Logo: string
}

class SportTeamAway {
  + Id: int
  + Name: string
  + Logo: string
}

class SportGameLeague {
  + Id: int
  + Name: string
  + Type: string
  + Logo: string
  + Season: int
}

class SportGameParameters {
  + Date: string
}

class SportResponse {
  + Id: int
  + Date: DateTime
  + Time: string
  + Timestamp: int
  + Timezone: string
  + Status: SportStatus
  + Country: SportCountry
  + League: SportGameLeague
  + Teams: SportTeams
  + Score: SportScore
  + Periods: SportPeriods
}

class SportScore {
  + Home: int?
  + Away: int?
}

class SportStatus {
  + long: string
  + short: string
  + elapsed: int?
}

class SportTeams {
  + Home: SportTeamHome
  + Away: SportTeamAway
}

class SportCountry {
  + Id: int?
  + Name: string
  + Code: string?
  + Flag: string?
}

class SportPeriods {
  + First: SportFirst?
  + Second: SportSecond?
}

class SportFirst {
  + HomePoints: int?
  + AwayPoints: int?
}

class SportSecond {
  + HomePoints: int?
  + AwayPoints: int?
}

SportTeamAway --o SportTeams : Aggregazione
SportTeamHome --o SportTeams : Aggregazione
SportGameLeague --o SportResponse : Aggregazione
SportGameParameters --* Sport : Composizione
SportResponse --* Sport : Composizione
SportScore --* SportResponse : Composizione
SportStatus --* SportResponse : Composizione
SportTeams --* SportResponse : Composizione
SportCountry --* SportResponse : Composizione
SportPeriods --* SportResponse : Composizione
SportFirst --* SportPeriods : Composizione
SportSecond --* SportPeriods : Composizione
Sportify *- HomePage : includes
HomePage <|-- Sport
SportifyController --> Sport

@enduml