@startuml class_diagram
class Sportify {
  +run(): void
}

class HomePage {
  - sport: String
}

class Football {
  - leagues: List<LeagueModel>

  + GoToLeague(league: LeagueModel): Task
}

class FootballStandings {
  - standingColor: Color
  - scorerColor: Color
  - fixtureColor: Color
  - league: LeagueModel
  - rankingsVisible: bool
  - topScorerVisible: bool
  - fixturesVisible: bool
  - seasons: List<string>
  - id: string
  - football: Football
  - groups: ObservableCollection<string>
  - previousGroup: string
  - topScorers: FootballTopScorers
  - gameDay: GameDay
  - _selectedSeason: string

  + SelectedSeasonFootball: string
  + ShowLeagues(): Task
  + ShowTopScorers(): Task
  + ShowFixtures(): Task
}

class Hockey {
  - isBusy: bool
  - hockeyGame: ObservableCollection<HockeyGameResponse>
  - hockeyLeague: HockeyGameLeague
  - _selectedDate: DateTime

  + SelectedDate: DateTime
  + ShowGames(): Task
  + GoToHockeyDetailsGame(hockeyGame: HockeyGameResponse): Task
}

class HockeyDetails {
  - hockeyGame: HockeyGameResponse

  + HockeyDetailsGameController(hockeyGame: HockeyGameResponse)
}

class Rugby {
  - isBusy: bool
  - rugbyGame: List<RugbyGameResponse>
  - rugbyLeague: RugbyLeague
  - _selectedDate: DateTime

  + SelectedDate: DateTime
  + HomeRugbyController()
  + ShowGames(): Task
  + GoToRugbyGameDetails(rugbyGame: RugbyGameResponse): Task
  + GoToLeagues(): Task
  + GoToHome(): Task
}

class RugbyLeagues {
  - rugbyLeagueStandings: RugbyLeagueStandingsModel
  - seasons: List<string>
  - _selectedSeason: string
  - isBusy: bool
  - rugbyLeagues: List<RugbyLeagueResponse>

  + SelectedSeasonLeagues: string
  + RugbyLeaguesController(rugbyLeague: RugbyLeague)
  + GetLeagues(): Task
  + GoToRugbyLeagueStandings(rugbyLeague: RugbyLeagueResponse): Task
}

class RugbyLeagues {
  +name: String
  +nation: String
  +season: int
}

' class RugbyStandings{
'   + position: int
'   + teamName: String
'   + points: int
'   + gamesPlayed: int
'   + win: int
'   + winPercentage: int
'   + draw: int
'   + drawPercentage: int
'   + lose: int
'   + losePercentage: int
'   + pointsFor: int
'   + pointsAgainst: int
' }

class FootballLeague {
  +name: String
}

class TopScorer {
  +name: String
  +goals: int
  +squad: String
  +appearances: int
  +total_shoots: int
  +penalty_scored: int
}

class Standing {
  +position: int
  +team: String
  +points: int
  +wins: int
  +draws: int
  +losses: int
  +goals_for: int
  +goals_against: int
  +goal_difference: int
}


Sportify *- HomePage : includes
HomePage <|-- Football
HomePage <|-- Rugby
HomePage <|-- Hockey
HomePage <|-- NBA
HomePage <|-- Formula1
HomePage <|-- Baseball
Football *- FootballStandings : has
Rugby *- RugbyLeagues : has
RugbyLeagues *- RugbyStandings : has
Hockey *- HockeyDetails : has

@enduml